//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ajay_dbEntities : DbContext
    {
        public ajay_dbEntities()
            : base("name=ajay_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegisterUser> RegisterUsers { get; set; }
        public virtual DbSet<Fiscalyear> Fiscalyears { get; set; }
        public virtual DbSet<LogDetail> LogDetails { get; set; }
        public virtual DbSet<MemberRegistration> MemberRegistrations { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PlanMaster> PlanMasters { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual DbSet<SchemeMaster> SchemeMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_COURSE_SUBJECT_MAPPING_DETAILS> TBL_COURSE_SUBJECT_MAPPING_DETAILS { get; set; }
        public virtual DbSet<TBL_GN_ANNOUNCEMENT> TBL_GN_ANNOUNCEMENT { get; set; }
        public virtual DbSet<TBL_GN_DIGITALDOC_DETAILS> TBL_GN_DIGITALDOC_DETAILS { get; set; }
        public virtual DbSet<TBL_GN_DIGITALDOC_VIEWDETAILS> TBL_GN_DIGITALDOC_VIEWDETAILS { get; set; }
        public virtual DbSet<TBL_MASTER_BOARDS> TBL_MASTER_BOARDS { get; set; }
        public virtual DbSet<TBL_MASTER_CITY> TBL_MASTER_CITY { get; set; }
        public virtual DbSet<TBL_MASTER_CLASS> TBL_MASTER_CLASS { get; set; }
        public virtual DbSet<TBL_MASTER_COUNTRY> TBL_MASTER_COUNTRY { get; set; }
        public virtual DbSet<TBL_MASTER_COURSE> TBL_MASTER_COURSE { get; set; }
        public virtual DbSet<TBL_MASTER_DIGITALDOC> TBL_MASTER_DIGITALDOC { get; set; }
        public virtual DbSet<TBL_MASTER_DOCUMENTTYPE> TBL_MASTER_DOCUMENTTYPE { get; set; }
        public virtual DbSet<TBL_MASTER_STATE> TBL_MASTER_STATE { get; set; }
        public virtual DbSet<TBL_MASTER_STATUS> TBL_MASTER_STATUS { get; set; }
        public virtual DbSet<TBL_MASTER_SUBJECT> TBL_MASTER_SUBJECT { get; set; }
        public virtual DbSet<TBL_MASTER_TEACHER> TBL_MASTER_TEACHER { get; set; }
        public virtual DbSet<TBL_MASTER_TEST_TYPE> TBL_MASTER_TEST_TYPE { get; set; }
        public virtual DbSet<TBL_MASTER_TESTQUESTIONTYPE> TBL_MASTER_TESTQUESTIONTYPE { get; set; }
        public virtual DbSet<TBL_MASTER_USERTYPE> TBL_MASTER_USERTYPE { get; set; }
        public virtual DbSet<TBL_STUDENT_MASTER_MAPPING> TBL_STUDENT_MASTER_MAPPING { get; set; }
        public virtual DbSet<TBL_TEACHER_COURSE_MAPPING_DETAILS> TBL_TEACHER_COURSE_MAPPING_DETAILS { get; set; }
        public virtual DbSet<TBL_TEACHER_SUBJECT_MAPPING_DETAILS> TBL_TEACHER_SUBJECT_MAPPING_DETAILS { get; set; }
        public virtual DbSet<TBL_TEST_ANSWERS> TBL_TEST_ANSWERS { get; set; }
        public virtual DbSet<TBL_TEST_ATAMPT> TBL_TEST_ATAMPT { get; set; }
        public virtual DbSet<TBL_TEST_ATAMPT_QUESTION_ANSWER> TBL_TEST_ATAMPT_QUESTION_ANSWER { get; set; }
        public virtual DbSet<TBL_TEST_QUESTIONS> TBL_TEST_QUESTIONS { get; set; }
        public virtual DbSet<TBL_TEST_TESTDETAIL> TBL_TEST_TESTDETAIL { get; set; }
        public virtual DbSet<TBL_USER_ADDRESS_DETAILS> TBL_USER_ADDRESS_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_COURSE_DETAILS> TBL_USER_COURSE_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_COURSE_MAPPING_DETAILS> TBL_USER_COURSE_MAPPING_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_DETAILS> TBL_USER_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_DOCUMENTS_DETAILS> TBL_USER_DOCUMENTS_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_INSTITUTION_DETAILS> TBL_USER_INSTITUTION_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_LOGIN> TBL_USER_LOGIN { get; set; }
        public virtual DbSet<TBL_USER_LOGIN_TRAIL> TBL_USER_LOGIN_TRAIL { get; set; }
        public virtual DbSet<TBL_USER_PARENTS_DETAILS> TBL_USER_PARENTS_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_PROFESSIONAL_DETAILS> TBL_USER_PROFESSIONAL_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_ROLE> TBL_USER_ROLE { get; set; }
        public virtual DbSet<TBL_USER_SUBJECTS> TBL_USER_SUBJECTS { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
