//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDetail
    {
        public long LogId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string MessageId { get; set; }
        public string MessageMethod { get; set; }
    }
}
