//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENT_MASTER_MAPPING
    {
        public long STUDENTMASTERID { get; set; }
        public Nullable<long> COURSEID { get; set; }
        public Nullable<long> PARENTID { get; set; }
        public Nullable<long> PROFESSIONALDETAILID { get; set; }
        public Nullable<long> STUDENTID { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<long> USERDOCUMENTID { get; set; }
        public Nullable<long> ROLEID { get; set; }
    }
}
