//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_PROFESSIONAL_DETAILS
    {
        public long PROFESSIONALDETAILID { get; set; }
        public Nullable<long> USERID { get; set; }
        public string COMPANYNAME { get; set; }
        public string DESIGNATION { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<long> CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> MODIFIEDDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual TBL_USER_LOGIN TBL_USER_LOGIN { get; set; }
    }
}
