//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MASTER_TESTQUESTIONTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MASTER_TESTQUESTIONTYPE()
        {
            this.TBL_TEST_QUESTIONS = new HashSet<TBL_TEST_QUESTIONS>();
        }
    
        public int QUESTIONTYPEID { get; set; }
        public string TYPENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_QUESTIONS> TBL_TEST_QUESTIONS { get; set; }
    }
}
