//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_PARENTS_DETAILS
    {
        public long PARENTID { get; set; }
        public Nullable<long> USERID { get; set; }
        public string FATHERNAME { get; set; }
        public string FATHEREMAIL { get; set; }
        public string FATHERMOBILENUMBER { get; set; }
        public string FATHEROCCUPATION { get; set; }
        public string FATHERCOMPANYNAME { get; set; }
        public string FATHERDESIGNATION { get; set; }
        public string MOTHERNAME { get; set; }
        public string MOTHEREMAIL { get; set; }
        public string MOTHERMOBILENUMBER { get; set; }
        public string MOTHEROCCUPATION { get; set; }
        public string MOTHERCOMPANYNAME { get; set; }
        public string MOTHERDESIGNATION { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual TBL_USER_LOGIN TBL_USER_LOGIN { get; set; }
    }
}
