//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEST_ATAMPT_QUESTION_ANSWER
    {
        public long ATAMPTTESTANSWERID { get; set; }
        public Nullable<long> QUESTIONID { get; set; }
        public Nullable<long> ANSWERID { get; set; }
        public Nullable<long> TESTID { get; set; }
        public string REMARKS { get; set; }
    
        public virtual TBL_TEST_QUESTIONS TBL_TEST_QUESTIONS { get; set; }
        public virtual TBL_TEST_TESTDETAIL TBL_TEST_TESTDETAIL { get; set; }
    }
}
