//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEST_TESTDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TEST_TESTDETAIL()
        {
            this.TBL_TEST_ANSWERS = new HashSet<TBL_TEST_ANSWERS>();
            this.TBL_TEST_ATAMPT = new HashSet<TBL_TEST_ATAMPT>();
            this.TBL_TEST_ATAMPT_QUESTION_ANSWER = new HashSet<TBL_TEST_ATAMPT_QUESTION_ANSWER>();
            this.TBL_TEST_QUESTIONS = new HashSet<TBL_TEST_QUESTIONS>();
        }
    
        public long TESTID { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> SUBJECTID { get; set; }
        public Nullable<System.DateTime> PUBLISHDATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<long> GIVENBY { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<int> COURSEID { get; set; }
        public Nullable<int> TESTTYPEID { get; set; }
        public Nullable<int> TOTALMARKS { get; set; }
        public Nullable<int> TOTALTIME { get; set; }
    
        public virtual TBL_MASTER_SUBJECT TBL_MASTER_SUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_ANSWERS> TBL_TEST_ANSWERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_ATAMPT> TBL_TEST_ATAMPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_ATAMPT_QUESTION_ANSWER> TBL_TEST_ATAMPT_QUESTION_ANSWER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_QUESTIONS> TBL_TEST_QUESTIONS { get; set; }
    }
}
