//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MASTER_STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MASTER_STATE()
        {
            this.TBL_MASTER_CITY = new HashSet<TBL_MASTER_CITY>();
        }
    
        public int STATEID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MASTER_CITY> TBL_MASTER_CITY { get; set; }
        public virtual TBL_MASTER_COUNTRY TBL_MASTER_COUNTRY { get; set; }
    }
}
