//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MASTER_SUBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MASTER_SUBJECT()
        {
            this.TBL_GN_DIGITALDOC_DETAILS = new HashSet<TBL_GN_DIGITALDOC_DETAILS>();
            this.TBL_TEST_TESTDETAIL = new HashSet<TBL_TEST_TESTDETAIL>();
            this.TBL_USER_SUBJECTS = new HashSet<TBL_USER_SUBJECTS>();
        }
    
        public int SUBJECTID { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_GN_DIGITALDOC_DETAILS> TBL_GN_DIGITALDOC_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_TESTDETAIL> TBL_TEST_TESTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USER_SUBJECTS> TBL_USER_SUBJECTS { get; set; }
    }
}
