//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEST_QUESTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TEST_QUESTIONS()
        {
            this.TBL_TEST_ANSWERS = new HashSet<TBL_TEST_ANSWERS>();
            this.TBL_TEST_ATAMPT_QUESTION_ANSWER = new HashSet<TBL_TEST_ATAMPT_QUESTION_ANSWER>();
        }
    
        public long QUESTIONID { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ISMULTISELECT { get; set; }
        public long TESTID { get; set; }
        public int QUESTIONTYPEID { get; set; }
        public int MARKS { get; set; }
    
        public virtual TBL_MASTER_TESTQUESTIONTYPE TBL_MASTER_TESTQUESTIONTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_ANSWERS> TBL_TEST_ANSWERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEST_ATAMPT_QUESTION_ANSWER> TBL_TEST_ATAMPT_QUESTION_ANSWER { get; set; }
        public virtual TBL_TEST_TESTDETAIL TBL_TEST_TESTDETAIL { get; set; }
    }
}
