//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GN_DIGITALDOC_VIEWDETAILS
    {
        public long DOCVIEWID { get; set; }
        public Nullable<long> DIGITALDOCID { get; set; }
        public Nullable<long> VIEWBY { get; set; }
        public Nullable<long> DOWNLOADBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual TBL_GN_DIGITALDOC_DETAILS TBL_GN_DIGITALDOC_DETAILS { get; set; }
    }
}
