//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_ADDRESS_DETAILS
    {
        public long ADDRESSDETAILID { get; set; }
        public long USERID { get; set; }
        public int ADDRESSTYPEID { get; set; }
        public string ADDRESSLINE1 { get; set; }
        public string ADDRESSLINE2 { get; set; }
        public Nullable<int> CITY { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public string PINCODE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
    
        public virtual TBL_USER_LOGIN TBL_USER_LOGIN { get; set; }
    }
}
